global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"

scrape_configs:
  - job_name: node
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: cadvisor
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: app
    static_configs:
    - targets: ['app:3000']

  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: loki
    static_configs:
      - targets: ['loki:3100']

  - job_name: caddy
    static_configs:
      - targets: ['caddy:2019']
