server:
  disable: true

positions:
  filename: loki-positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: containers 
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag

      - regex:
          expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
          source: "tag"

      - labels:
          tag:
          stream:
          image_name:
          container_name:
          image_id:
          container_id:

    static_configs:
      - labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*log
          # __path__: /var/lib/docker/containers/*/*-json.log

